pub enum PushCodes {
    Advert,
    PathUpdated,
    SendConfirmed,
    MsgWaiting,
    RawData,
    LoginSuccess,
    LoginFail,
    StatusResponse,
    LogRxData,
    TraceData,
    NewAdvert,
    TelemetryResponse,
    BinaryResponse,
    ControlData,
}
